spring.application.name=demo
spring.profiles.active=dev

server.port=8080

jwt.secret=12345678901234567890123456789012
jwt.expiration-ms=86400000

springdoc.swagger-ui.path=/swagger-ui.html
springdoc.api-docs.path=/v3/api-docs